### ISSUE TITLE
class:AfterMount 함수 가능한가요?

### ISSUE THREAD

**Issue by AyoWhat-satanred1** [qwreey75/Quad#4]
인자로 mount 된 클래스 오게끔요
클래스 내부에서 update 를 하고싶은데 할 방법이 없어보입니다 ㅠㅠ

(Feature Request)

**Comment by qwreey** [comment]
AfterRender 라는 메소드가 존재하긴 합니다
그러나 주의하셔야 할 점은 이 라이브러리는 타겟이 gtk 와 같은 다른 백엔드도 있기 때문에 해당 메소드가 받는 인자는 달라질 수 있습니다.
기본적인 상황에서는 Render 함수가 반환한 객체를 줍니다 (rbx 내에선 Instance 이거나 class 의 instance)

또한 self ""; 를 통해서 클래스에 특정 키에 원하는 인스턴스를 바인딩 할 수도 있습니다. 그 후 AfterRender 에서 해당하는걸 사용하실 수 있습니다

```lua
function myclass:Render(props)
  return Frame {
    Name = "a";
    Frame {
      self "_frame"; -- 언더바는 권장입니다. 그렇게 해야 값 변경됨을 트리거 하지 않습니다
      Name = "b";
    }
  }
end
function myclass:AfterRender(root)
  print(root.Name) -- a
  print(self._frame.Name) -- b
end
```

다만 AfterRender 가 트리거 된다고 바로 ui 가 반응성을 얻은 상태 (화면에 보여지는 상태) 는 아닐 수 있습니다
반응성이 검사돠어야할 필요가 있다면 인자 받은걸 IsAncestorOf 돌려야 할 수도 있습니다

렌더 최상층 부분에 AncestryChanged 이벤트 거시고 this 받은거에 IsAncestorOf 걸어서 game 안에 있는지 확인 하시고 self 에 다른 메소드 하나 넣어서 그거 트리거 해주시면 ui 가 보여질 때 트리거도 가능합니다

```lua
function myclass:Render(props)
  return Frame {
    AncestryChanged = function(this)
      if this:IsAncestorOf(game) then
        self:Displayed()
    end;
    Name = "a";
    Frame {
      self "_frame"; -- 언더바는 권장입니다. 그렇게 해야 값 변경됨을 트리거 하지 않습니다
      Name = "b";
    }
  }
end
function myclass:Displayed()
  print("화면에 보여집니다")
end

```

저가 생각하기에도 이건 너무 해키한 방안이다 싶어 좀 개선해야할 부분이긴 하겠네요
화면이 표시 될 때 트리거도 만들긴 해야겠습니다..

**Comment by AyoWhat-satanred1** [comment]
감사합니다 :>
